// Generated by https://quicktype.io

export interface AuthInterfaceTs {
  user: User
  token: string
}

export interface Market {
  id: number
  name: string
}

export interface User {
  id: number
  uuid: string
  email: string
  name: string
  last_name: string
  id_number: string
  company_name: string
  role_id: 2 | 3
  company_id: number
  inserted_at: string
  updated_at: string
  markets: number[]
  markets_name: string[]
  all_markets: Market[]
}
