// Generated by https://quicktype.io

export interface Bid {
  id: number
  status: string
  uuid: string
  origin_id: number
  origin_name: string
  origin_country: string
  destination_id: number
  destination_name: string
  destination_country: string
  transportation: string
  comex_type: string
  expiration_date: string
  shipping_type: string
  value: string
  currency: string
  additional_info: string
  user_id: number
  market_id: number
  bid_details_id: number
  inserted_at: string
}

export interface Incoterm {
  id: number
  name: string
  spanish_name: string
  english_name: string
}
